# Generated by Django 4.2.5 on 2023-09-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_number', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
