# Generated by Django 4.2.5 on 2023-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InletData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_id', models.IntegerField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('iteration', models.IntegerField(max_length=10)),
                ('cpu_time', models.DecimalField(decimal_places=4, max_digits=4)),
                ('value', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='OutletData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_id', models.IntegerField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('iteration', models.IntegerField(max_length=10)),
                ('cpu_time', models.DecimalField(decimal_places=4, max_digits=4)),
                ('value', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PumpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_id', models.IntegerField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=4)),
                ('velocity', models.DecimalField(decimal_places=4, max_digits=4)),
                ('average', models.DecimalField(decimal_places=4, max_digits=4)),
                ('flow', models.DecimalField(decimal_places=4, max_digits=4)),
                ('rate_persec', models.DecimalField(decimal_places=4, max_digits=4)),
                ('temp', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
    ]
