# Generated by Django 4.2.5 on 2023-12-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='outflow',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='pump',
            old_name='datetime',
            new_name='date',
        ),
    ]
