# Generated by Django 4.2.5 on 2023-10-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_inletdata_outletdata_pumpdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inletdata',
            name='cpu_time',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='outletdata',
            name='cpu_time',
            field=models.IntegerField(max_length=10),
        ),
    ]
