# Generated by Django 4.2.5 on 2023-12-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_datetime_inflow_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadLog',
        ),
    ]
