# Generated by Django 4.2.6 on 2023-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_inletdata_cpu_time_alter_outletdata_cpu_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.BigIntegerField(blank=True, db_column='Iteration', null=True)),
                ('cputime', models.BigIntegerField(blank=True, db_column='CPUTime', null=True)),
                ('phystime', models.BigIntegerField(blank=True, db_column='PhysTime', null=True)),
                ('travels', models.FloatField(blank=True, db_column='Travels', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('avvalue', models.FloatField(blank=True, db_column='AvValue', null=True)),
                ('minvalue', models.FloatField(blank=True, db_column='MinValue', null=True)),
                ('maxvalue', models.FloatField(blank=True, db_column='MaxValue', null=True)),
                ('delta', models.FloatField(blank=True, db_column='Delta', null=True)),
                ('criteria', models.FloatField(blank=True, db_column='Criteria', null=True)),
                ('prevavrefvalue', models.BigIntegerField(blank=True, db_column='PrevAvRefValue', null=True)),
                ('progress', models.FloatField(blank=True, db_column='Progress', null=True)),
                ('criteriatype', models.BigIntegerField(blank=True, db_column='CriteriaType', null=True)),
                ('criteriavartype', models.BigIntegerField(blank=True, db_column='CriteriaVarType', null=True)),
                ('criteriapercentage', models.BigIntegerField(blank=True, db_column='CriteriaPercentage', null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('batteryid', models.BigIntegerField(blank=True, db_column='batteryID', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.BigIntegerField(blank=True, db_column='Iteration', null=True)),
                ('cputime', models.BigIntegerField(blank=True, db_column='CPUTime', null=True)),
                ('phystime', models.BigIntegerField(blank=True, db_column='PhysTime', null=True)),
                ('travels', models.FloatField(blank=True, db_column='Travels', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('avvalue', models.FloatField(blank=True, db_column='AvValue', null=True)),
                ('minvalue', models.FloatField(blank=True, db_column='MinValue', null=True)),
                ('maxvalue', models.FloatField(blank=True, db_column='MaxValue', null=True)),
                ('delta', models.FloatField(blank=True, db_column='Delta', null=True)),
                ('criteria', models.FloatField(blank=True, db_column='Criteria', null=True)),
                ('prevavrefvalue', models.BigIntegerField(blank=True, db_column='PrevAvRefValue', null=True)),
                ('progress', models.BigIntegerField(blank=True, db_column='Progress', null=True)),
                ('criteriatype', models.BigIntegerField(blank=True, db_column='CriteriaType', null=True)),
                ('criteriavartype', models.BigIntegerField(blank=True, db_column='CriteriaVarType', null=True)),
                ('criteriapercentage', models.BigIntegerField(blank=True, db_column='CriteriaPercentage', null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('batteryid', models.BigIntegerField(blank=True, db_column='batteryID', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.FloatField(blank=True, db_column='W', null=True)),
                ('v', models.FloatField(blank=True, db_column='V', null=True)),
                ('a', models.FloatField(blank=True, db_column='A', null=True)),
                ('flow_l_min', models.FloatField(blank=True, db_column='flow', null=True)),
                ('r_sec', models.BigIntegerField(blank=True, db_column='rPersec', null=True)),
                ('temp_field', models.FloatField(blank=True, db_column='Temp', null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('batteryid', models.BigIntegerField(blank=True, db_column='batteryID', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InletData',
        ),
        migrations.DeleteModel(
            name='OutletData',
        ),
        migrations.DeleteModel(
            name='PumpData',
        ),
    ]
